version = 0.1
[default.deploy.parameters]
stack_name = "bixi-api"
resolve_s3 = true
s3_prefix = "bixi-api"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
