AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Bixi-Api

Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128
    Timeout: 100
    LoggingConfig:
      LogFormat: JSON

Resources:
  BixiApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Tags:
        Name: !Sub "${AWS::StackName}-API"
        Stack: !Sub "${AWS::StackName}"

  TripDurationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: trip_duration/
      Handler: app.lambda_handler
      Description: Handler for all trip duration related operations
      Events:
        TripDurationApi:
          Type: Api
          Properties:
            Path: /trip-durations/average
            Method: get
            RestApiId: !Ref BixiApi

Outputs:
  TripDurationAverageEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Trip Duration Average function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/trip-durations/average/"
  TripDurationFunction:
    Description: Trip Duration Lambda Function ARN
    Value: !GetAtt TripDurationFunction.Arn
  TripDurationFunctionIamRole:
    Description: Implicit IAM Role created for Trip Duration function
    Value: !GetAtt TripDurationFunctionRole.Arn
