@startmindmap routes
* /
** /trips
*** /duration/average?min_start_time=&max_start_time=
*** /time
**** /start
***** /minimum
***** /maximum
**** /end
***** /minimum
***** /maximum
** /health
** /docs
@endmindmap
