@startmindmap routes
* /
** /trips
*** /duration/average?startStationName=&endStationName=&minStartTime=&maxStartTime=
*** /time
**** /start
***** /minimum
***** /maximum
**** /end
***** /minimum
***** /maximum
** /stations
*** /arrondissements
*** /stations?name=&arrondissement=
** /health
** /docs

@endmindmap
