name: Lint and test

on:
  workflow_call:
    inputs:
      deploy-test-coverage:
        description: Whether to deploy test coverage to Github Pages
        required: true
        default: false
        type: boolean

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r tests/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --max-line-length=127 --statistics --exclude=.aws-sam

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r tests/requirements.txt

      - name: Run tests
        run: pytest tests/

      # - name: Configure pages
      #   if: ${{ inputs.deploy-test-coverage }}
      #   uses: actions/configure-pages@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload artifact
      #   if: ${{ inputs.deploy-test-coverage }}
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     name: test-coverage
      #     path: ./coverage/lcov-report

      # - name: Deploy to GitHub Pages
      #   if: ${{ inputs.deploy-test-coverage }}
      #   id: deployment
      #   uses: actions/deploy-pages@v2
      #   with:
      #     artifact_name: test-coverage
