name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    name: Build and Deploy to AWS

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Build and Deploy to AWS
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          MONGO_DATABASE_NAME: ${{ vars.MONGO_DATABASE_NAME }}
          BIXI_LOCATION_COLLECTION: ${{ vars.BIXI_LOCATION_COLLECTION }}
          BIXI_TRIP_COLLECTION: ${{ vars.BIXI_TRIP_COLLECTION }}
          BIXI_CACHE_COLLECTION: ${{ vars.BIXI_CACHE_COLLECTION }}
          BIXI_TRIP_CACHE_TTL: ${{ vars.BIXI_TRIP_CACHE_TTL }}
        run: |
          sam build
          sam deploy --parameter-overrides \
            AtlasUri=$ATLAS_URI \
            MongoDatabaseName=$MONGO_DATABASE_NAME \
            BixiLocationCollection=$BIXI_LOCATION_COLLECTION \
            BixiTripCollection=$BIXI_TRIP_COLLECTION \
            BixiCacheCollection=$BIXI_CACHE_COLLECTION \
            BixiTripCacheTtl=$BIXI_TRIP_CACHE_TTL
