name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  # Allows the manual execution of the workflow from the Action tab
  workflow_dispatch:
   inputs:
      enable_deployment:
        description: 'Deploy to GitHub Pages? (true/false)'
        required: true
        default: false
        type: boolean

jobs:
  lint-and-test:
    name: Lint, test and deploy test coverage to Github Pages
    uses: ./.github/actions/lint-test/lint-test-workflow.yml@feature/rework-pipeline
    with:
      deploy: ${{ github.event.inputs.enable_deployment }}

  security-and-analysis:
    name: Security, code analysis and deploy analysis to Github Pages
    uses: ./.github/actions/security-analysis/security-analysis-workflow.yml
    with:
      deploy: ${{ github.event.inputs.enable_deployment }}

