name: Continuous Integration

on:
  pull_request:
    branches:
      - main

  # Allows the manual execution of the workflow from the Action tab
  workflow_dispatch:

jobs:
  
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "Placeholder job, does nothing."

  # lint-and-test:
  #   uses: ./.github/workflows/lint-test-workflow.yml
  #   with:
  #     deploy-test-coverage: false
