name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  ############# remove when secrets key are configured! #############
  lint-and-test:
    name: Lint, test and deploy test coverage to Github Pages
    uses: ./.github/workflows/lint-test-workflow.yml
    with:
      deploy: ${{ github.event.inputs.enable_deployment }}

  # deploy:
  #   name: Deploy to AWS
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #   
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1-node16
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ca-central-1 

  #     - name: Build and Deploy to AWS
  #       env:
  #         BIXI_API_URL: ${{ secrets.BIXI_API_URL }}
  #         BIXI_API_KEY: ${{ secrets.BIXI_API_KEY }}
  #       run: |
  #         sam build
  #         sam deploy --parameter-overrides ApiUrl=$STM_API_URL ApiKey=$STM_API_KEY
